Repository yzharko/spbspu-labs-2024-tp, pull requests merged in 2024-05, with the labels that each got.

#61 tellez.aron/T2
  tellez.aron/T2/dataStruct.cpp
  tellez.aron/T2/dataStruct.hpp
  tellez.aron/T2/delimeter.cpp
  tellez.aron/T2/delimeter.hpp
  tellez.aron/T2/main.cpp
  tellez.aron/T2/value.cpp
  tellez.aron/T2/value.hpp
Labels: .ok

#53 hohlova.polina/T2
  hohlova.polina/T2/dataStruct.hpp
  hohlova.polina/T2/delimiter.cpp
  hohlova.polina/T2/delimiter.hpp
  hohlova.polina/T2/iofmtguard.cpp
  hohlova.polina/T2/iofmtguard.hpp
  hohlova.polina/T2/main.cpp
  hohlova.polina/T2/types.cpp
  hohlova.polina/T2/types.hpp
  hohlova.polina/T2/yaDataStruct.cpp
  hohlova.polina/T2/yaDataStruct.hpp
Labels: .ok

#58 popov.nikita/T2
  popov.nikita/T2/dataStruct.cpp
  popov.nikita/T2/dataStruct.hpp
  popov.nikita/T2/delimeter.cpp
  popov.nikita/T2/delimeter.hpp
  popov.nikita/T2/iofmtguard.cpp
  popov.nikita/T2/iofmtguard.hpp
  popov.nikita/T2/main.cpp
  popov.nikita/T2/structData.cpp
  popov.nikita/T2/structData.hpp
Labels: .ok

#42 litsinger.ernest/T2
  litsinger.ernest/T2/dataTypes.cpp
  litsinger.ernest/T2/dataTypes.hpp
  litsinger.ernest/T2/datastruct.cpp
  litsinger.ernest/T2/datastruct.hpp
  litsinger.ernest/T2/delimiters.cpp
  litsinger.ernest/T2/delimiters.hpp
  litsinger.ernest/T2/main.cpp
  litsinger.ernest/T2/scopeguard.cpp
  litsinger.ernest/T2/scopeguard.hpp
Labels: .ok

#68 redko.arina/T3
  redko.arina/T2/dataStruct.cpp
  redko.arina/T2/structures.cpp
  redko.arina/T3/commands.cpp
  redko.arina/T3/commands.hpp
  redko.arina/T3/main.cpp
  redko.arina/T3/shape.cpp
  redko.arina/T3/shape.hpp
  redko.arina/T3/shapeFunctions.cpp
  redko.arina/T3/shapeFunctions.hpp
  redko.arina/common/delimiter.cpp
  redko.arina/common/delimiter.hpp
Labels: .ok

#71 khoroshkin.maksim/T3
  khoroshkin.maksim/T3/commands.cpp
  khoroshkin.maksim/T3/commands.hpp
  khoroshkin.maksim/T3/main.cpp
  khoroshkin.maksim/T3/polygon.cpp
  khoroshkin.maksim/T3/polygon.hpp
  khoroshkin.maksim/common/datastruct.cpp
  khoroshkin.maksim/common/datastruct.hpp
  khoroshkin.maksim/common/delimiter.hpp
  khoroshkin.maksim/common/scopeguard.cpp
  khoroshkin.maksim/common/scopeguard.hpp
Labels: .ok

#45 zhitnyj.dmitriy/T2
  zhitnyj.dmitriy/T2/DataStruct.cpp
  zhitnyj.dmitriy/T2/DataStruct.hpp
  zhitnyj.dmitriy/T2/DelStrIO.hpp
  zhitnyj.dmitriy/T2/DelimiterIO.hpp
  zhitnyj.dmitriy/T2/StringIO.hpp
  zhitnyj.dmitriy/T2/UllHexIO.hpp
  zhitnyj.dmitriy/T2/UllLitIO.hpp
  zhitnyj.dmitriy/T2/iofmtguard.cpp
  zhitnyj.dmitriy/T2/iofmtguard.hpp
  zhitnyj.dmitriy/T2/main.cpp
Labels: .ok

#74 miheev.egor/T3
  miheev.egor/T3/commands.cpp
  miheev.egor/T3/commands.hpp
  miheev.egor/T3/dataTypes.cpp
  miheev.egor/T3/dataTypes.hpp
  miheev.egor/T3/geometry.cpp
  miheev.egor/T3/geometry.hpp
  miheev.egor/T3/main.cpp
  miheev.egor/common/delimiters.cpp
  miheev.egor/common/delimiters.hpp
  miheev.egor/common/scopeguard.cpp
  miheev.egor/common/scopeguard.hpp
Labels: .ok

#69 psarev.alexandr/T3
  psarev.alexandr/T3/commands.cpp
  psarev.alexandr/T3/commands.hpp
  psarev.alexandr/T3/internalFuncs.cpp
  psarev.alexandr/T3/internalFuncs.hpp
  psarev.alexandr/T3/main.cpp
  psarev.alexandr/T3/polygon.cpp
  psarev.alexandr/T3/polygon.hpp
  psarev.alexandr/common/delim.cpp
  psarev.alexandr/common/delim.hpp
  psarev.alexandr/common/scopeGuard.cpp
  psarev.alexandr/common/scopeGuard.hpp
Labels: .ok

#73 sobolevsky.misha/T3
  sobolevsky.misha/T2/dataStruct.hpp
  sobolevsky.misha/T3/commands.cpp
  sobolevsky.misha/T3/commands.hpp
  sobolevsky.misha/T3/main.cpp
  sobolevsky.misha/T3/point.cpp
  sobolevsky.misha/T3/point.hpp
  sobolevsky.misha/T3/polygon.cpp
  sobolevsky.misha/T3/polygon.hpp
  sobolevsky.misha/common/helpStructs.cpp
  sobolevsky.misha/common/helpStructs.hpp
Labels: .ok

#51 sadofeva.nastya/T2
  sadofeva.nastya/T2/datastruct.cpp
  sadofeva.nastya/T2/datastruct.hpp
  sadofeva.nastya/T2/delimiter.hpp
  sadofeva.nastya/T2/guard.cpp
  sadofeva.nastya/T2/guard.hpp
  sadofeva.nastya/T2/main.cpp
Labels: .ok

#65 sukacheva.maria/T2
  sukacheva.maria/T2/DataStruct.cpp
  sukacheva.maria/T2/DataStruct.hpp
  sukacheva.maria/T2/Delimeter.cpp
  sukacheva.maria/T2/Delimeter.hpp
  sukacheva.maria/T2/KeyStruct.cpp
  sukacheva.maria/T2/KeyStruct.hpp
  sukacheva.maria/T2/StreamGuard.cpp
  sukacheva.maria/T2/StreamGuard.hpp
  sukacheva.maria/T2/main.cpp
Labels: .ok

#56 gorbunova.alena/T2
  gorbunova.alena/T2/anotherStructs.hpp
  gorbunova.alena/T2/dataStruct.cpp
  gorbunova.alena/T2/dataStruct.hpp
  gorbunova.alena/T2/delimiter.cpp
  gorbunova.alena/T2/delimiter.hpp
  gorbunova.alena/T2/iofmtguard.cpp
  gorbunova.alena/T2/iofmtguard.hpp
  gorbunova.alena/T2/main.cpp
  gorbunova.alena/T2/yaDataStruct.cpp
  gorbunova.alena/T2/yaDataStruct.hpp
Labels: .ok

#72 nikiforov.alexander/T3
  nikiforov.alexander/T3/commands.cpp
  nikiforov.alexander/T3/commands.hpp
  nikiforov.alexander/T3/dataStruct.cpp
  nikiforov.alexander/T3/dataStruct.hpp
  nikiforov.alexander/T3/main.cpp
  nikiforov.alexander/common/delimiter.cpp
  nikiforov.alexander/common/delimiter.hpp
Labels: .ok

#79 ponomarev.viacheslav/T3
  ponomarev.viacheslav/T3/commands.cpp
  ponomarev.viacheslav/T3/commands.hpp
  ponomarev.viacheslav/T3/main.cpp
  ponomarev.viacheslav/T3/polygon.cpp
  ponomarev.viacheslav/T3/polygon.hpp
  ponomarev.viacheslav/T3/polygonFunctions.cpp
  ponomarev.viacheslav/T3/polygonFunctions.hpp
  ponomarev.viacheslav/common/delimiter.cpp
  ponomarev.viacheslav/common/delimiter.hpp
Labels: .ok

#77 jirkov.vladimir/T2
  jirkov.vladimir/T2/DataStruct.cpp
  jirkov.vladimir/T2/DataStruct.hpp
  jirkov.vladimir/T2/DelimiterIO.hpp
  jirkov.vladimir/T2/IOstructures.cpp
  jirkov.vladimir/T2/IOstructures.hpp
  jirkov.vladimir/T2/ScopeGuard.cpp
  jirkov.vladimir/T2/ScopeGuard.hpp
  jirkov.vladimir/T2/StringIO.hpp
  jirkov.vladimir/T2/UllLitIO.hpp
  jirkov.vladimir/T2/UllOctIO.hpp
  jirkov.vladimir/T2/main.cpp
Labels: .ok

#83 doroshenko.anna/T3
  doroshenko.anna/T3/commands.cpp
  doroshenko.anna/T3/commands.hpp
  doroshenko.anna/T3/main.cpp
  doroshenko.anna/T3/polygon.cpp
  doroshenko.anna/T3/polygon.hpp
  doroshenko.anna/common/scopeGuard.cpp
  doroshenko.anna/common/scopeGuard.hpp
  doroshenko.anna/common/structures.cpp
  doroshenko.anna/common/structures.hpp
Labels: .ok

#85 zhitnyj.dmitriy/T3
  zhitnyj.dmitriy/T2/DataStruct.cpp
  zhitnyj.dmitriy/T2/DelStrIO.hpp
  zhitnyj.dmitriy/T2/iofmtguard.hpp
  zhitnyj.dmitriy/T3/Commands.cpp
  zhitnyj.dmitriy/T3/Commands.hpp
  zhitnyj.dmitriy/T3/FileReader.cpp
  zhitnyj.dmitriy/T3/FileReader.hpp
  zhitnyj.dmitriy/T3/GeometryUtils.cpp
  zhitnyj.dmitriy/T3/GeometryUtils.hpp
  zhitnyj.dmitriy/T3/Point.cpp
  zhitnyj.dmitriy/T3/Point.hpp
  zhitnyj.dmitriy/T3/Polygon.cpp
  zhitnyj.dmitriy/T3/Polygon.hpp
  zhitnyj.dmitriy/T3/main.cpp
  zhitnyj.dmitriy/common/DelimiterIO.cpp
  zhitnyj.dmitriy/common/DelimiterIO.hpp
  zhitnyj.dmitriy/common/iofmtguard.cpp
  zhitnyj.dmitriy/common/iofmtguard.hpp
Labels: .ok

#86 reznikova.anna/T3
  reznikova.anna/T3/Commands.cpp
  reznikova.anna/T3/Commands.hpp
  reznikova.anna/T3/FigureStructs.cpp
  reznikova.anna/T3/FigureStructs.hpp
  reznikova.anna/T3/InputProcessing.cpp
  reznikova.anna/T3/InputProcessing.hpp
  reznikova.anna/T3/main.cpp
  reznikova.anna/common/Delimeter.cpp
  reznikova.anna/common/Delimeter.hpp
  reznikova.anna/common/ScopeGuard.cpp
  reznikova.anna/common/ScopeGuard.hpp
Labels: .ok

#87 sukacheva.maria/T3
  sukacheva.maria/T3/ErrorMessage.cpp
  sukacheva.maria/T3/ErrorMessage.hpp
  sukacheva.maria/T3/commands.cpp
  sukacheva.maria/T3/commands.hpp
  sukacheva.maria/T3/main.cpp
  sukacheva.maria/T3/struct.cpp
  sukacheva.maria/T3/struct.hpp
  sukacheva.maria/common/Delimeter.cpp
  sukacheva.maria/common/Delimeter.hpp
  sukacheva.maria/common/StreamGuard.cpp
  sukacheva.maria/common/StreamGuard.hpp
Labels: .ok

#78 kovshikov.nikita/T3
  kovshikov.nikita/T3/commands.cpp
  kovshikov.nikita/T3/commands.hpp
  kovshikov.nikita/T3/for_commands.cpp
  kovshikov.nikita/T3/for_commands.hpp
  kovshikov.nikita/T3/main.cpp
  kovshikov.nikita/T3/point.cpp
  kovshikov.nikita/T3/point.hpp
  kovshikov.nikita/T3/polygons.cpp
  kovshikov.nikita/T3/polygons.hpp
  kovshikov.nikita/common/io_structures.cpp
  kovshikov.nikita/common/io_structures.hpp
  kovshikov.nikita/common/scope_guard.cpp
  kovshikov.nikita/common/scope_guard.hpp
Labels: .ok

#81 zheleznyakov.mark/T3
  zheleznyakov.mark/T3/commands.cpp
  zheleznyakov.mark/T3/commands.hpp
  zheleznyakov.mark/T3/dataTypes.cpp
  zheleznyakov.mark/T3/dataTypes.hpp
  zheleznyakov.mark/T3/geometry.cpp
  zheleznyakov.mark/T3/geometry.hpp
  zheleznyakov.mark/T3/main.cpp
  zheleznyakov.mark/common/iofmtguard.cpp
  zheleznyakov.mark/common/iofmtguard.hpp
  zheleznyakov.mark/common/separators.cpp
  zheleznyakov.mark/common/separators.hpp
Labels: .ok

#91 anikanov.vladislav/T3
  anikanov.vladislav/T2/inOutPut.cpp
  anikanov.vladislav/T2/inOutPut.hpp
  anikanov.vladislav/T2/main.cpp
  anikanov.vladislav/T3/main.cpp
  anikanov.vladislav/T3/mainExtensions.cpp
  anikanov.vladislav/T3/mainExtensions.hpp
  anikanov.vladislav/T3/point.hpp
  anikanov.vladislav/T3/polygon.cpp
  anikanov.vladislav/T3/polygon.hpp
  anikanov.vladislav/common/delimiter.hpp
  anikanov.vladislav/common/guard.hpp
  anikanov.vladislav/common/inDelim.cpp
  anikanov.vladislav/common/inDelim.hpp
Labels: .ok

#82 miheev.egor/F0
  miheev.egor/F0/IOFunctions.cpp
  miheev.egor/F0/IOFunctions.hpp
  miheev.egor/F0/commands.cpp
  miheev.egor/F0/commands.hpp
  miheev.egor/F0/graph.cpp
  miheev.egor/F0/graph.hpp
  miheev.egor/F0/main.cpp
  miheev.egor/F0/workspace.hpp
Labels: .ok, 4/5

#88 sobolevsky.misha/F0
  sobolevsky.misha/F0/main.cpp
  sobolevsky.misha/F0/mycommands.cpp
  sobolevsky.misha/F0/mycommands.hpp
Labels: .ok, 3/5

#89 nikiforov.alexander/F0
  nikiforov.alexander/F0/commands.cpp
  nikiforov.alexander/F0/commands.hpp
  nikiforov.alexander/F0/main.cpp
  nikiforov.alexander/F0/menu.cpp
  nikiforov.alexander/F0/menu.hpp
Labels: .ok, 4/5

#92 kovshikov.nikita/F0
  kovshikov.nikita/F0/createGraph.cpp
  kovshikov.nikita/F0/createGraph.hpp
  kovshikov.nikita/F0/main.cpp
  kovshikov.nikita/F0/orientedGraph.cpp
  kovshikov.nikita/F0/orientedGraph.hpp
  kovshikov.nikita/F0/outMessage.hpp
  kovshikov.nikita/F0/workingGraph.cpp
  kovshikov.nikita/F0/workingGraph.hpp
Labels: .ok, 4/5

#94 redko.arina/F0
  redko.arina/F0/HuffmanCode.cpp
  redko.arina/F0/HuffmanCode.hpp
  redko.arina/F0/main.cpp
  redko.arina/F0/processingFunctions.cpp
  redko.arina/F0/processingFunctions.hpp
  redko.arina/F0/userCommands.cpp
  redko.arina/F0/userCommands.hpp
Labels: .ok, 5/5

#95 sukacheva.maria/F0
  sukacheva.maria/F0/commands.cpp
  sukacheva.maria/F0/commands.hpp
  sukacheva.maria/F0/graph.cpp
  sukacheva.maria/F0/graph.hpp
  sukacheva.maria/F0/main.cpp
  sukacheva.maria/F0/workspace.cpp
  sukacheva.maria/F0/workspace.hpp
Labels: .ok, 4/5

#96 doroshenko.anna/F0
  doroshenko.anna/F0/commands.cpp
  doroshenko.anna/F0/commands.hpp
  doroshenko.anna/F0/main.cpp
Labels: .ok, 4/5

#98 taskaev.matvei/F0
  taskaev.matvei/F0/HuffmanTree.cpp
  taskaev.matvei/F0/HuffmanTree.hpp
  taskaev.matvei/F0/command.cpp
  taskaev.matvei/F0/command.hpp
  taskaev.matvei/F0/main.cpp
Labels: .ok, 3/5

#99 psarev.alexandr/F0
  psarev.alexandr/F0/internalFuncs.cpp
  psarev.alexandr/F0/internalFuncs.hpp
  psarev.alexandr/F0/main.cpp
  psarev.alexandr/F0/userCmds.cpp
  psarev.alexandr/F0/userCmds.hpp
Labels: .ok, 4/5

#101 reznikova.anna/F0
  reznikova.anna/F0/Commands.cpp
  reznikova.anna/F0/Commands.hpp
  reznikova.anna/F0/Graph.cpp
  reznikova.anna/F0/Graph.hpp
  reznikova.anna/F0/Vertex.cpp
  reznikova.anna/F0/Vertex.hpp
  reznikova.anna/F0/WorkSpace.cpp
  reznikova.anna/F0/WorkSpace.hpp
  reznikova.anna/F0/main.cpp
Labels: .ok, 5/5

#102 mihalchenko.vladislav/F0
  mihalchenko.vladislav/F0/commands.cpp
  mihalchenko.vladislav/F0/commands.hpp
  mihalchenko.vladislav/F0/details.hpp
  mihalchenko.vladislav/F0/helpDelimiters.cpp
  mihalchenko.vladislav/F0/helpDelimiters.hpp
  mihalchenko.vladislav/F0/helpFunctions.cpp
  mihalchenko.vladislav/F0/helpFunctions.hpp
  mihalchenko.vladislav/F0/main.cpp
Labels: .ok, 5/5

#103 anikanov.vladislav/F0
  anikanov.vladislav/F0/changeMenuScene.cpp
  anikanov.vladislav/F0/changeMenuScene.hpp
  anikanov.vladislav/F0/graphMenuScene.cpp
  anikanov.vladislav/F0/graphMenuScene.hpp
  anikanov.vladislav/F0/main.cpp
  anikanov.vladislav/F0/mainMenuScene.cpp
  anikanov.vladislav/F0/mainMenuScene.hpp
  anikanov.vladislav/F0/myAlgorithms.cpp
  anikanov.vladislav/F0/myAlgorithms.hpp
  anikanov.vladislav/F0/runMatrixScene.cpp
  anikanov.vladislav/F0/runMatrixScene.hpp
  anikanov.vladislav/F0/scene.cpp
  anikanov.vladislav/F0/scene.hpp
  anikanov.vladislav/F0/sceneManager.cpp
  anikanov.vladislav/F0/sceneManager.hpp
  anikanov.vladislav/F0/settings.cpp
  anikanov.vladislav/F0/settings.hpp
Labels: .ok, 4/5

#104 zhitnyj.dmitriy/F0
  zhitnyj.dmitriy/F0/Commands.cpp
  zhitnyj.dmitriy/F0/Commands.hpp
  zhitnyj.dmitriy/F0/Graph.hpp
  zhitnyj.dmitriy/F0/GraphUtils.cpp
  zhitnyj.dmitriy/F0/GraphUtils.hpp
  zhitnyj.dmitriy/F0/main.cpp
Labels: .ok, 3/5
