Repository yzharko/spbspu-labs-2024-tp, pull requests merged in 2024-09, with the labels that each got.

#67 panov.ilya/T2
  panov.ilya/DataStruct.cpp
  panov.ilya/DataStruct.h
  panov.ilya/main.cpp
Labels: .furyDobs

#75 kaseev.andrey/T2
  kaseev.andrey/T2/DataStruct.cpp
  kaseev.andrey/T2/DataStruct.hpp
  kaseev.andrey/T2/Delimetor.cpp
  kaseev.andrey/T2/Delimetor.hpp
  kaseev.andrey/T2/ScopeGuard.cpp
  kaseev.andrey/T2/ScopeGuard.hpp
  kaseev.andrey/T2/main.cpp
Labels: .furyDobs

#84 hohlova.polina/T3
  hohlova.polina/T3/commands.cpp
  hohlova.polina/T3/commands.hpp
  hohlova.polina/T3/main.cpp
  hohlova.polina/T3/polygon.cpp
  hohlova.polina/T3/polygon.hpp
  hohlova.polina/common/delimiter.cpp
  hohlova.polina/common/delimiter.hpp
  hohlova.polina/common/iofmtguard.cpp
  hohlova.polina/common/iofmtguard.hpp
Labels: .furyDobs

#105 jirkov.vladimir/T3
  jirkov.vladimir/T2/DataStruct.cpp
  jirkov.vladimir/T2/DataStruct.hpp
  jirkov.vladimir/T2/IOstructures.cpp
  jirkov.vladimir/T2/IOstructures.hpp
  jirkov.vladimir/T2/StringIO.hpp
  jirkov.vladimir/T2/UllLitIO.hpp
  jirkov.vladimir/T2/UllOctIO.hpp
  jirkov.vladimir/T2/main.cpp
  jirkov.vladimir/T3/Commands.cpp
  jirkov.vladimir/T3/Commands.hpp
  jirkov.vladimir/T3/main.cpp
  jirkov.vladimir/T3/point.cpp
  jirkov.vladimir/T3/point.hpp
  jirkov.vladimir/T3/polygons.cpp
  jirkov.vladimir/T3/polygons.hpp
  jirkov.vladimir/common/DelimiterIO.hpp
  jirkov.vladimir/common/IOstructures.cpp
  jirkov.vladimir/common/IOstructures.hpp
  jirkov.vladimir/common/ScopeGuard.cpp
  jirkov.vladimir/common/ScopeGuard.hpp
Labels: .furyDobs

#106 gorbunova.alena/T3
  gorbunova.alena/T3/commands.cpp
  gorbunova.alena/T3/commands.hpp
  gorbunova.alena/T3/main.cpp
  gorbunova.alena/T3/polygon.cpp
  gorbunova.alena/T3/polygon.hpp
  gorbunova.alena/common/delimiter.cpp
  gorbunova.alena/common/delimiter.hpp
  gorbunova.alena/common/iofmtguard.cpp
  gorbunova.alena/common/iofmtguard.hpp
Labels: .furyDobs

#107 popov.nikita/T3
  popov.nikita/T3/commands.cpp
  popov.nikita/T3/commands.hpp
  popov.nikita/T3/main.cpp
  popov.nikita/T3/polygon.cpp
  popov.nikita/T3/polygon.hpp
  popov.nikita/common/delimeter.cpp
  popov.nikita/common/delimeter.hpp
  popov.nikita/common/iofmtguard.cpp
  popov.nikita/common/iofmtguard.hpp
Labels: .furyDobs

#108 lisitsyna.yulia/T3
  lisitsyna.yulia/T3/Delimeter.cpp
  lisitsyna.yulia/T3/Delimeter.hpp
  lisitsyna.yulia/T3/ScopeGuard.cpp
  lisitsyna.yulia/T3/ScopeGuard.hpp
  lisitsyna.yulia/T3/commands.cpp
  lisitsyna.yulia/T3/commands.hpp
  lisitsyna.yulia/T3/main.cpp
  lisitsyna.yulia/T3/polygon.cpp
  lisitsyna.yulia/T3/polygon.hpp
Labels: .furyDobs

#109 litsinger.ernest/T3
  litsinger.ernest/T3/Commands.cpp
  litsinger.ernest/T3/Commands.hpp
  litsinger.ernest/T3/Delimeter.cpp
  litsinger.ernest/T3/Delimeter.hpp
  litsinger.ernest/T3/FigureStructs.cpp
  litsinger.ernest/T3/FigureStructs.hpp
  litsinger.ernest/T3/InputProcessing.cpp
  litsinger.ernest/T3/InputProcessing.hpp
  litsinger.ernest/T3/ScopeGuard.cpp
  litsinger.ernest/T3/ScopeGuard.hpp
  litsinger.ernest/T3/main.cpp
Labels: .furyDobs

#110 sadofeva.nastya/T3
  sadofeva.nastya/T3/Point.cpp
  sadofeva.nastya/T3/Point.hpp
  sadofeva.nastya/T3/command.cpp
  sadofeva.nastya/T3/command.hpp
  sadofeva.nastya/T3/main.cpp
  sadofeva.nastya/common/datastruct.cpp
  sadofeva.nastya/common/datastruct.hpp
  sadofeva.nastya/common/delimiter.hpp
  sadofeva.nastya/common/guard.cpp
  sadofeva.nastya/common/guard.hpp
Labels: .furyDobs

#112 ankhbayar.battsolmon/T2
  battsolmon.ankhbayar/T2/dataStruct.cpp
  battsolmon.ankhbayar/T2/dataStruct.hpp
  battsolmon.ankhbayar/T2/main.cpp
Labels: .furyDobs

#114 proselkov.stanislav/T2
  proselkov.stanislav/T2/DataStruct.cpp
  proselkov.stanislav/T2/DataStruct.hpp
  proselkov.stanislav/T2/main.cpp
Labels: .furyDobs

#128 khomichenko.alisa/T2
  khomichenko.alisa/T2/dataStruct.cpp
  khomichenko.alisa/T2/dataStruct.hpp
  khomichenko.alisa/T2/helpers.cpp
  khomichenko.alisa/T2/helpers.hpp
  khomichenko.alisa/T2/main.cpp
  khomichenko.alisa/T2/scopeGuard.cpp
  khomichenko.alisa/T2/scopeGuard.hpp
Labels: .furyDobs

#129 batunov.roman/T2
  batunov.roman/T2/DataStruct.cpp
  batunov.roman/T2/DataStruct.h
  batunov.roman/T2/main.cpp
Labels: .furyDobs

#115 sadofeva.nastya/F0
  sadofeva.nastya/F0/command.cpp
  sadofeva.nastya/F0/command.hpp
  sadofeva.nastya/F0/helpcommand.cpp
  sadofeva.nastya/F0/helpcommand.hpp
  sadofeva.nastya/F0/main.cpp
  sadofeva.nastya/F0/processor.cpp
  sadofeva.nastya/F0/processor.hpp
Labels: .furyDobs

#130 batunov.roman/T3
  batunov.roman/T3/Commands.cpp
  batunov.roman/T3/Commands.h
  batunov.roman/T3/Iofmtguard.cpp
  batunov.roman/T3/Iofmtguard.h
  batunov.roman/T3/Polygon.cpp
  batunov.roman/T3/Polygon.h
  batunov.roman/T3/main.cpp
Labels: .furyDobs

#122 maksimov.leonid/T3
  maksimov.leonid/T3/Commands.cpp
  maksimov.leonid/T3/Commands.hpp
  maksimov.leonid/T3/DelimiterI.cpp
  maksimov.leonid/T3/DelimiterI.hpp
  maksimov.leonid/T3/Shapes.cpp
  maksimov.leonid/T3/Shapes.hpp
  maksimov.leonid/T3/main.cpp
Labels: .furyDobs

#132 maksimov.leonid/F0
  maksimov.leonid/F0/commands.cpp
  maksimov.leonid/F0/commands.hpp
  maksimov.leonid/F0/dict.cpp
  maksimov.leonid/F0/dict.hpp
  maksimov.leonid/F0/main.cpp
Labels: .furyDobs

#136 smolyakov.alexander/T0
  smolyakov.alexander/T0/main.cpp
Labels: .furyDobs

#117 hohlova.polina/f0
  hohlova.polina/F0/commands.cpp
  hohlova.polina/F0/commands.hpp
  hohlova.polina/F0/main.cpp
Labels: .furyDobs

#134 khomichenko.alisa/T3
  khomichenko.alisa/T3/commands.cpp
  khomichenko.alisa/T3/commands.hpp
  khomichenko.alisa/T3/helpers.cpp
  khomichenko.alisa/T3/helpers.hpp
  khomichenko.alisa/T3/main.cpp
  khomichenko.alisa/T3/polygon.cpp
  khomichenko.alisa/T3/polygon.hpp
Labels: .furyDobs

#138 khomichenko.alisa/F0
  khomichenko.alisa/F0/cmd.cpp
  khomichenko.alisa/F0/cmd.hpp
  khomichenko.alisa/F0/input.cpp
  khomichenko.alisa/F0/input.hpp
  khomichenko.alisa/F0/main.cpp
  khomichenko.alisa/F0/utilities.cpp
  khomichenko.alisa/F0/utilities.hpp
Labels: .furyDobs

#120 litsinger.ernest/F0
  litsinger.ernest/F0/commands.cpp
  litsinger.ernest/F0/commands.hpp
  litsinger.ernest/F0/main.cpp
Labels: .furyDobs

#118 proselkov.stanislav/T3
  proselkov.stanislav/T3/Commands.cpp
  proselkov.stanislav/T3/Commands.hpp
  proselkov.stanislav/T3/Iofmtguard.cpp
  proselkov.stanislav/T3/Iofmtguard.hpp
  proselkov.stanislav/T3/Polygon.cpp
  proselkov.stanislav/T3/Polygon.hpp
  proselkov.stanislav/T3/main.cpp
Labels: .furyDobs

#137 panov.ilya/T2
  panov.ilya/DataStruct.cpp
  panov.ilya/DataStruct.h
  panov.ilya/T2/data_struct.cpp
  panov.ilya/T2/data_struct.hpp
  panov.ilya/T2/io_structures.cpp
  panov.ilya/T2/io_structures.hpp
  panov.ilya/T2/main.cpp
  panov.ilya/T2/scope_guard.cpp
  panov.ilya/T2/scope_guard.hpp
  panov.ilya/main.cpp
Labels: .furyDobs

#124 malanin.nikita/T2
  malanin.nikita/T2/DataStruct.cpp
  malanin.nikita/T2/DataStruct.hpp
  malanin.nikita/T2/delimeter.cpp
  malanin.nikita/T2/delimeter.hpp
  malanin.nikita/T2/main.cpp
  malanin.nikita/T2/value.cpp
  malanin.nikita/T2/value.hpp
Labels: .furyDobs

#116 panov.ilya/T3
  panov.ilya/T3/Commands.cpp
  panov.ilya/T3/Commands.hpp
  panov.ilya/T3/Delimeter.cpp
  panov.ilya/T3/Delimeter.hpp
  panov.ilya/T3/Polygon.cpp
  panov.ilya/T3/Polygon.hpp
  panov.ilya/T3/StreamGuard.cpp
  panov.ilya/T3/StreamGuard.hpp
  panov.ilya/T3/Utilies.cpp
  panov.ilya/T3/Utilies.hpp
  panov.ilya/T3/main.cpp
Labels: .furyDobs

#121 panov.ilya/F0
  panov.ilya/F0/commands.cpp
  panov.ilya/F0/commands.hpp
  panov.ilya/F0/dicts.hpp
  panov.ilya/F0/main.cpp
Labels: .furyDobs

#123 popov.nikita/F0
  popov.nikita/F0/commands.cpp
  popov.nikita/F0/commands.hpp
  popov.nikita/F0/main.cpp
Labels: .furyDobs

#131 batunov.roman/F0
  batunov.roman/F0/Dictionary.cpp
  batunov.roman/F0/Dictionary.h
  batunov.roman/F0/DictionaryManager.cpp
  batunov.roman/F0/DictionaryManager.h
  batunov.roman/F0/main.cpp
Labels: .furyDobs

#142 jirkov.vladimir/T2
  jirkov.vladimir/common/DataStruct.cpp
  jirkov.vladimir/common/DataStruct.hpp
  jirkov.vladimir/common/IOstructures.cpp
  jirkov.vladimir/common/IOstructures.hpp
  jirkov.vladimir/common/StringIO.hpp
  jirkov.vladimir/common/UllLitIO.hpp
  jirkov.vladimir/common/UllOctIO.hpp
Labels: .derSchwarzePunkt

#135 kaseev.andrey/T3
  kaseev.andrey/T3/Commands.cpp
  kaseev.andrey/T3/Commands.hpp
  kaseev.andrey/T3/Iofmtguard.cpp
  kaseev.andrey/T3/Iofmtguard.hpp
  kaseev.andrey/T3/Polygon.cpp
  kaseev.andrey/T3/Polygon.hpp
  kaseev.andrey/T3/main.cpp
Labels: .furyDobs

#141 malanin.nikita/T3
  malanin.nikita/T3/Commands.cpp
  malanin.nikita/T3/Commands.hpp
  malanin.nikita/T3/Delimiters.cpp
  malanin.nikita/T3/Delimiters.hpp
  malanin.nikita/T3/Polygon.cpp
  malanin.nikita/T3/Polygon.hpp
  malanin.nikita/T3/StreamGuard.cpp
  malanin.nikita/T3/StreamGuard.hpp
  malanin.nikita/T3/main.cpp
Labels: .furyDobs

#146 kaseev.andrey/F0
  kaseev.andrey/F0/functions.cpp
  kaseev.andrey/F0/functions.hpp
  kaseev.andrey/F0/main.cpp
Labels: .furyDobs

#143 smolyakov.alexander/T2
  smolyakov.alexander/T2/DataStruct.cpp
  smolyakov.alexander/T2/DataStruct.hpp
  smolyakov.alexander/T2/RatLsp.cpp
  smolyakov.alexander/T2/RatLsp.hpp
  smolyakov.alexander/T2/ScopeGuard.cpp
  smolyakov.alexander/T2/ScopeGuard.hpp
  smolyakov.alexander/T2/StringWrapper.cpp
  smolyakov.alexander/T2/StringWrapper.hpp
  smolyakov.alexander/T2/StructInputSeparator.cpp
  smolyakov.alexander/T2/StructInputSeparator.hpp
  smolyakov.alexander/T2/UllOct.cpp
  smolyakov.alexander/T2/UllOct.hpp
  smolyakov.alexander/T2/main.cpp
Labels: .furyDobs

#139 uzun.oguldzhan/T0
  uzun.oguldzhan/T0/main.cpp
Labels: .ok, .furyDobs

#119 proselkov.stanislav/F0
  proselkov.stanislav/F0/commands.cpp
  proselkov.stanislav/F0/commands.hpp
  proselkov.stanislav/F0/main.cpp
Labels: .furyDobs

#148 susidko.fedor/T2
  susidko.fedor/T2/DataStruct.cpp
  susidko.fedor/T2/DataStruct.hpp
  susidko.fedor/T2/DelAnd.cpp
  susidko.fedor/T2/DelAnd.hpp
  susidko.fedor/T2/main.cpp
Labels: .furyDobs
